### ISSUE TITLE
Discussion on imagined renderings of the views and view components

### ISSUE THREAD

**Issue by mahendrark** [rl-institut/open_plan#30]
There must be a file where we can note down the potential  renderings we imagine for view-components and views of the tool. 
We can also describe the renderings/interface right here on this issue. 

Your thoughts @Bachibouzouk and @TheOneAndra?

**Comment by Bachibouzouk** [comment]
I think it is fine to gather it here

**Comment by mahendrark** [comment]
Rendering of the create scenario view component:

* There should be a button with the label 'Create Scenario'
* When the user clicks on Current Scenario, a pop-up appears (typically of most OSs) where the user can specify the path of the repository/scenario_object name or graphically move around the file/folder structure
* A button with a label 'Create' is placed adjacent to the text field located at the bottom of the pop-up window, which when clicked saves the scenario object and then the scenario object shows up in the list of available scenarios on the scenarios view

**Comment by mahendrark** [comment]
@TheOneAndra and @Bachibouzouk 

First, I want to raise the issue of the logo. 

This is not an important issue. So take your time please.

1. I assume it would be a view-component.
2. Would it be only on the landing page? or appear on multiple pages

Second, about the landing page...

If the user checks the box to hide the welcome message pop-up showing up on subsequent launches of the tool, what should we display in place of that on the landing page? Surely it cant be empty space.

**Comment by TheOneAndra** [comment]
1. I agree that the logo is not an important issue, especially because this is an open_source tool. We can just put it outside the view window (on the top of the window where you can close the app, like most of the tools). Therefore it would not be a view component and would probably not even be in the RDT. 

2. I understood the landing page as the welcome pop-up message. Therefore, if the user clicks on "do not show this again", next time the tool is opened, the first page is the first of the flow chart.
