### ISSUE TITLE
Imprint and Privacy pages are missing

### ISSUE THREAD

**Issue by bmlancien** [rl-institut/open_plan#84]
@catcad @Bachibouzouk  should we use the text from the RLI website? If yes, there are still a few things we should change though: there won't be any tracking tool, right? Will there be some cookies on the website?

**Comment by Bachibouzouk** [comment]
I am not in favor of a tracking tool, if is it only up to me we don't have tracking tool :)
Cookies I don't think so either

**Comment by catcad** [comment]
Hi,
I agree. No tracking tool necessary, if we can avoid cookies it’ll be great since I hate these agree to cookie pop up thing.
Thanks,
Catherina

Von: Pierre Francois <notifications@github.com>
Gesendet: Montag, 16. November 2020 11:08
An: rl-institut/open_plan <open_plan@noreply.github.com>
Cc: Catherina Cader <Catherina.Cader@rl-institut.de>; Assign <assign@noreply.github.com>
Betreff: [extern] Re: [rl-institut/open_plan] Imprint and Privacy pages are missing (#84)


I am not in favor of a tracking tool, if is it only up to me we don't have tracking tool :)
Cookies I don't think so either
