### ISSUE TITLE
Website feedbacks

### ISSUE THREAD

**Issue by TheOneAndra** [rl-institut/open_plan#94]
https://open-plan.herokuapp.com/

**Comment by mahendrark** [comment]
I went through the website and I do not have many comments except very minor grammatical ones. I think its very good overall. 

Here are my really insignificant suggestions:

1. In the subtext of the heading, practitioners seems a bit vague. Can add something like "practitioners of energy modelling". Same with project developers. 'Energy project developers'. 

2. Typo in the line 'If you want to collaborate or are interested in the project, you can find more informations on'. It should be information.

**Comment by catcad** [comment]
Here are a few comments from my side:

- [ ] please change the bold part in the text [...]EEG into italic instead of bold since the heading is already in bold.
![grafik](https://user-images.githubusercontent.com/33006916/100882051-00117f80-34af-11eb-8482-9ced340d2e33.png)

- [ ] Publications site is still not available. Here is already one document which could be linked there: https://reiner-lemoine-institut.de/wp-content/uploads/2020/07/open-plan_Stakeholder_Workshop_Zusammenfassung.pdf 

- [x] Please change User friendly to User friendliness
![grafik](https://user-images.githubusercontent.com/33006916/100882958-0eac6680-34b0-11eb-8b22-a26902f04f88.png)

- [x] Please change the logo into the English version as saved here: \\fs01\RL-Institut\04_Projekte\299_open_plan\05-OeA\Logo\BMWi\Foerderzusatz_BMWi_en\Gefoerdert_en\ 

- [x] Please add a full stop at the end of the sentence in the footer:
![grafik](https://user-images.githubusercontent.com/33006916/100886849-95fbd900-34b4-11eb-9481-8572f646e1a4.png)

- [x] Please exclude the minus in open-license:
![grafik](https://user-images.githubusercontent.com/33006916/100887026-ca6f9500-34b4-11eb-9e6a-a384e11f5569.png)

- [x] Please uncapitalize the I in BMWi in the About us section
![grafik](https://user-images.githubusercontent.com/33006916/100888015-e9baf200-34b5-11eb-873d-d458323930a6.png)

 - [x] Please add in the About us section: "The open_plan project consortium is composed of the Reiner Lemoine Institut (RLI), Deutsche Gesellschaft für Sonnenenergie (DGS) and the Potsdam Institut für Klimafolgenforschung (PIK)."

**Comment by catcad** [comment]
The projects listed under stakeholder dialogue are not the same as related projects below:

Q1: Shall we harmonize them or is there a reason behind the selection?
Q2: Shall we create a link to the projects within the stakeholder dialogue text?

![grafik](https://user-images.githubusercontent.com/33006916/100887587-6ac5b980-34b5-11eb-8a4b-6793ec20617b.png)

**Comment by catcad** [comment]
From a design perspective I wonder if it makes sense that the logo on top is smaller then later below?
What is your opinion @bmlancien ?
![grafik](https://user-images.githubusercontent.com/33006916/100888801-c6dd0d80-34b6-11eb-9ce3-41e4e02d3e53.png)

**Comment by Bachibouzouk** [comment]
@catcad I updated the webapp with @bmlancien changes

**Comment by bmlancien** [comment]
@catcad 

> please change the bold part in the text [...]EEG into italic instead of bold since the heading is already in bold.

This is a [link](https://www.bmwi.de/Redaktion/DE/Downloads/G/gesetzentwurf-aenderung-erneuerbare-energien-gesetzes-und-weiterer-energierechtlicher-vorschriften.pdf?__blob=publicationFile&v=4), that's why this is in bold. I would rather keep it that way unless we remove the link, of course.

> Publications site is still not available. Here is already one document which could be linked there: https://reiner-lemoine-institut.de/wp-content/uploads/2020/07/open-plan_Stakeholder_Workshop_Zusammenfassung.pdf

Do you mean I should link the PDF from the "Publications" button and hide the publications page?

> Q1: Shall we harmonize them or is there a reason behind the selection?
Q2: Shall we create a link to the projects within the stakeholder dialogue text?

Q1: I only copied/pasted what was on the RLI website, I think. So, yes, we can harmonize it. Can you please give me a new text for that part?
Q2: Sure, we can!

> From a design perspective I wonder if it makes sense that the logo on top is smaller then later below?

I'm not really sure about that one, but I can try to harmonize the logos on that page to see how it looks like

**Comment by bmlancien** [comment]
> From a design perspective I wonder if it makes sense that the logo on top is smaller then later below?

I harmonized the logo sizes on #99 
I find a larger logo at the top of the website a bit distracting. It makes the text less important and therefore less visible. Should I try to reduce the size of all the open_plan logos instead?

**Comment by TheOneAndra** [comment]
![grafik](https://user-images.githubusercontent.com/66671861/101785595-3da08900-3afd-11eb-80a1-f826ebf049e4.png)


**Proposed texts (from top left corner then clockwise)**

The cellular approach is a new energy system model framework based on decentralized energy system and sector coupling.

The ground idea of the cellular approach is to balance energy consumption and energy production at the smallest level possible.

The cellular approach descirbes an energy system organized in so called energy cells.

An energy cell is a system composed of at least a generator, a converter, a storage unit, a load, a protection and control system and a connection to the distribution grid.

_any thoughts @catcad ?_

**Comment by catcad** [comment]
Hi Andra, 
thx, see below with a few minor changes of content and position
**Proposed texts (from top left corner then clockwise)**:

The cellular approach is a new energy system model framework based on decentralized energy systems and sector coupling.

The fundamental idea of the cellular approach is to balance energy consumption and energy production at the smallest level possible.

An energy cell is a system composed of at least a generator, a converter, a storage unit, an electric load supplied by a distribution grid and a protection and control system. _--> here I am not sure: is storage required? is it essential?_

The cellular approach describes an energy system organized in so-called energy cells.

**Comment by TheOneAndra** [comment]
> An energy cell is a system composed of at least a generator, a converter, a storage unit, an electric load supplied by a distribution grid and a protection and control system. 

This is wrong. The load doesn't _have_ to be eletric, it could be a thermal load as a cell can contain many forms of energy but can also contain 1, and it could be gas or thermal. 
>supplied by a distribution grid 

Enter in contradiction with "The fundamental idea of the cellular approach is to balance energy consumption and energy production at the smallest level possible."

>_--> here I am not sure: is storage required? is it essential?_

It is part of the definition.

**Instead of this paragraph, we could write:** 

An energy cell can contain many forms of energy such as electrcity, heat, gas, etc. A cell can also contain only one form of energy.

_(it would also make the text more linked to the picture)_

**Comment by catcad** [comment]
> This is wrong. The load doesn't have to be eletric, it could be a thermal load as a cell can contain many forms of energy but can also contain 1, and it could be gas or thermal.

I wouldn't say it is wrong since we say "at least" and I assume we would not look at a pure thermal system or gas system, no? But I agree that it may be misleading or limiting....

I'd suggest: 
An energy cell can contain and combine many forms of energy such as electricity, heat, gas, etc. 

I think "can" says that it can also be only one form.
What do you think @TheOneAndra ?

**Comment by TheOneAndra** [comment]
Summary for @bmlancien then: 

**Texts around the energy cell picture (from top left corner then clockwise):**

The cellular approach is a new energy system model framework based on decentralized energy systems and sector coupling.

The fundamental idea of the cellular approach is to balance energy consumption and energy production at the smallest level possible.

An energy cell can contain and combine many forms of energy such as electricity, heat, gas, etc.

The cellular approach describes an energy system organized in so-called energy cells.

**Comment by Bachibouzouk** [comment]
App is updated now (see RC for the link)

**Comment by catcad** [comment]
@bmlancien : can you please think of a different image for reproducibility?
![grafik](https://user-images.githubusercontent.com/33006916/103741262-0a1c2600-4ff9-11eb-9224-ec50b11514f0.png)

**Comment by Bachibouzouk** [comment]
@catcad - should we have a "last updated on <date>" on the website?
@bmlancien - do you know where it would nicely fit?

**Comment by bmlancien** [comment]
@Bachibouzouk Is it about new features/changes in the tool? If yes, maybe right below the "The open_plan tool is currently being developed" section?

**Comment by Bachibouzouk** [comment]
> @Bachibouzouk Is it about new features/changes in the tool? If yes, maybe right below the "The open_plan tool is currently being developed" section?

It is more to be able to let the people know how fresh the news/information on the website are

**Comment by bmlancien** [comment]
Ok, in that case I would add it under "Energy cells explained" or "Cross-sectoral, open-source planning tool". I think it's nice to have first the description of the project before seeing what's new, especially for new visitors.

**Comment by catcad** [comment]
We need to update the description of the document:
My suggestion: 

> Summary of the first stakeholder workshop on tool requirements. 

![grafik](https://user-images.githubusercontent.com/33006916/113714968-3ffca380-96e9-11eb-93a0-afee5d5c3370.png)

Who can implement it? Will it be @Bachibouzouk or @bmlancien ?

Also, please add the second workshop summary which can be found here: https://next.rl-institut.de/s/ictsnWKmMRD5ZHb 

My text suggestion would be:

> Summary of the second stakeholder workshop on tool functionalities.

**Comment by Bachibouzouk** [comment]
I will do it now :)
